-- ParentVeda — seed content_posts with the 10 posts that were hardcoded
-- in src/lib/guides.ts before the site moved to Supabase.
--
-- Generated by scratchpad/gen-migration.mjs from the preserved guides-old.ts.
-- Block[] bodies were converted to Markdown; the old "callout" block (the
-- medical disclaimer) became a "> Note: …" blockquote, which PostBody.tsx
-- renders as the same lavender callout panel.
--
-- Slugs, categories and dates are preserved exactly, so URLs and their SEO
-- are unchanged from the hardcoded era.
--
-- Safe to re-run: each statement inserts only if that (category, slug) is
-- absent, so nothing authored in Directus is ever overwritten. Re-running
-- will NOT update rows that already exist — edit those in Directus instead.
--
-- Run in: Supabase dashboard → SQL Editor.

-- article/eating-for-two-pregnancy-nutrition-myth
insert into public.content_posts (
  status, category, slug, title, description, excerpt, body, author,
  reading_time, tags, trimester, recipe, source, book_meta,
  published_at, updated_at
)
select
  'published',
  'article',
  'eating-for-two-pregnancy-nutrition-myth',
  'Eating for two? Why pregnancy nutrition isn''t about double portions',
  '“Eating for two” is a myth. Here''s what your body actually needs each trimester — calm, practical pregnancy nutrition without the pressure.',
  'The phrase sounds caring, but it leads to a lot of unnecessary worry. Here''s what real nourishment looks like, trimester by trimester.',
  '“You''re eating for two now!” is one of the first things many expecting mothers hear. It''s said with love — but it quietly suggests you should be eating twice as much. You don''t.

## How much extra do you really need?

For most of pregnancy, the extra energy your body needs is small — often nothing in the first trimester, and only a modest amount in the second and third. Think of it as a little more, not double.

- First trimester: usually no extra calories needed — focus on quality, not quantity.
- Second trimester: a small increase, roughly an extra snack a day.
- Third trimester: a little more again, as baby grows fastest.

## What actually matters

Nourishment matters far more than volume. Iron (palak, dal, gud), calcium (doodh, dahi, ragi, til), folate (leafy greens, citrus) and protein quietly do the heavy lifting. Small, frequent, warm meals are kinder on a queasy stomach than three large ones.

> Note: ParentVeda offers gentle, evidence-informed guidance — not medical advice. Always check with your doctor for decisions about your pregnancy.',
  'Team ParentVeda',
  '5 min read',
  ARRAY['nutrition', 'first trimester', 'weight']::text[],
  'first',
  NULL,
  NULL,
  NULL,
  '2026-05-12'::timestamptz,
  '2026-06-18'::timestamptz
where not exists (
  select 1 from public.content_posts
  where category = 'article' and slug = 'eating-for-two-pregnancy-nutrition-myth'
);

-- article/understanding-baby-movements-during-pregnancy
insert into public.content_posts (
  status, category, slug, title, description, excerpt, body, author,
  reading_time, tags, trimester, recipe, source, book_meta,
  published_at, updated_at
)
select
  'published',
  'article',
  'understanding-baby-movements-during-pregnancy',
  'Understanding your baby''s movements: what kicks and flutters mean',
  'When do baby kicks start, what''s normal, and when to call your doctor? A calm guide to fetal movement through the second and third trimesters.',
  'Those first flutters are unforgettable — and later, your baby''s pattern becomes a gentle daily reassurance. Here''s what to know.',
  'Somewhere around weeks 18–22, many mothers feel the first flutters — often mistaken for gas or a tiny bubble. These early movements are called quickening.

## How movement changes

As weeks pass, flutters become kicks, rolls and hiccups. By the third trimester, your baby settles into a pattern that''s unique to them — some are quiet in the morning and lively at night.

## Getting to know the pattern

There''s no single “correct” number of kicks. What matters is your baby''s own normal. Many mothers notice movement most when resting on their side after a meal.

> Note: If you ever notice a clear reduction or change in your baby''s usual movements, contact your doctor or hospital right away — it''s always okay to check. ParentVeda offers gentle, evidence-informed guidance — not medical advice. Always check with your doctor for decisions about your pregnancy.',
  'Team ParentVeda',
  '4 min read',
  ARRAY['second trimester', 'third trimester', 'baby movements']::text[],
  'second',
  NULL,
  NULL,
  NULL,
  '2026-05-20'::timestamptz,
  '2026-05-20'::timestamptz
where not exists (
  select 1 from public.content_posts
  where category = 'article' and slug = 'understanding-baby-movements-during-pregnancy'
);

-- research-summary/folic-acid-pregnancy-research-summary
insert into public.content_posts (
  status, category, slug, title, description, excerpt, body, author,
  reading_time, tags, trimester, recipe, source, book_meta,
  published_at, updated_at
)
select
  'published',
  'research-summary',
  'folic-acid-pregnancy-research-summary',
  'Folic acid before and during pregnancy: what the evidence says',
  'A plain-language summary of the research on folic acid in pregnancy — why 400 mcg daily is recommended and how it lowers neural tube defect risk.',
  'One of the most well-established findings in prenatal care, in plain language: what folic acid does and why timing matters.',
  'Among all prenatal advice, the case for folic acid is one of the strongest. Decades of research link adequate folate around conception with a markedly lower risk of neural tube defects such as spina bifida.

## What the studies show

- Folate is essential for the baby''s neural tube, which forms very early — often before a pregnancy is even confirmed.
- Major health bodies recommend roughly 400 micrograms of folic acid daily for those planning a pregnancy and through early pregnancy.
- Some people — for example with certain medical histories — may be advised a higher dose by their doctor.

## Why timing matters

Because the neural tube closes in the first weeks, starting before conception (or as early as possible) is what makes folic acid so effective. Food sources like leafy greens, dals and citrus help too, but a supplement is the dependable way to hit the target.

> Note: This is a general summary, not a prescription. ParentVeda offers gentle, evidence-informed guidance — not medical advice. Always check with your doctor for decisions about your pregnancy.',
  'Team ParentVeda',
  '5 min read',
  ARRAY['nutrition', 'supplements', 'first trimester']::text[],
  'first',
  NULL,
  '{"label":"Based on WHO and national health guidance on periconceptional folic acid supplementation."}'::jsonb,
  NULL,
  '2026-04-28'::timestamptz,
  '2026-06-10'::timestamptz
where not exists (
  select 1 from public.content_posts
  where category = 'research-summary' and slug = 'folic-acid-pregnancy-research-summary'
);

-- research-summary/prenatal-music-and-baby-research-summary
insert into public.content_posts (
  status, category, slug, title, description, excerpt, body, author,
  reading_time, tags, trimester, recipe, source, book_meta,
  published_at, updated_at
)
select
  'published',
  'research-summary',
  'prenatal-music-and-baby-research-summary',
  'Does prenatal music affect your baby? An honest look at the research',
  'Garbh Sanskar and prenatal music are deeply loved traditions. Here''s a calm, honest summary of what the science does — and doesn''t — show.',
  'Music in pregnancy is a beautiful ritual. We look at what research can actually tell us, without overclaiming.',
  'From the second trimester, your baby can hear muffled sounds — your voice, your heartbeat, and the world around you. It''s no surprise that traditions like Garbh Sanskar place music at the centre of pregnancy.

## What we can say

- Babies respond to sound in the womb — heart rate and movement can change with music or voices.
- Calm music can lower the mother''s stress, and a calmer mother is good for both of you.

## What we can''t claim

Strong, long-term claims — that a particular raga makes a baby smarter, for instance — aren''t well supported yet. The honest takeaway: enjoy music because it soothes you and bonds you, not because it''s a performance metric.

> Note: ParentVeda offers gentle, evidence-informed guidance — not medical advice. Always check with your doctor for decisions about your pregnancy.',
  'Team ParentVeda',
  '4 min read',
  ARRAY['garbh sanskar', 'wellbeing', 'third trimester']::text[],
  'third',
  NULL,
  '{"label":"Summarised from peer-reviewed studies on fetal hearing and maternal relaxation; evidence is still emerging."}'::jsonb,
  NULL,
  '2026-05-02'::timestamptz,
  '2026-05-02'::timestamptz
where not exists (
  select 1 from public.content_posts
  where category = 'research-summary' and slug = 'prenatal-music-and-baby-research-summary'
);

-- book-summary/what-to-expect-when-youre-expecting-summary
insert into public.content_posts (
  status, category, slug, title, description, excerpt, body, author,
  reading_time, tags, trimester, recipe, source, book_meta,
  published_at, updated_at
)
select
  'published',
  'book-summary',
  'what-to-expect-when-youre-expecting-summary',
  'What to Expect When You''re Expecting — a calm summary',
  'A short, honest summary of ''What to Expect When You''re Expecting'' — the key takeaways from the classic month-by-month pregnancy guide.',
  'The famous month-by-month companion, distilled to its most useful ideas — minus the information overload.',
  'Heidi Murkoff''s classic has guided generations of parents with its month-by-month, question-and-answer style. Here''s the gentle gist.

## Key takeaways

- Pregnancy unfolds in predictable stages — knowing roughly what each month brings reduces a lot of anxiety.
- Most symptoms are common and pass; the book''s reassurance is its real value.
- Preparation — questions for your doctor, a birth plan, a hospital bag — turns worry into action.

## Our calm note

The book is thorough, which can occasionally tip into overwhelm. Take what soothes you, skip what spikes worry, and remember that a guide is a companion — not a checklist to be graded on.

> Note: ParentVeda offers gentle, evidence-informed guidance — not medical advice. Always check with your doctor for decisions about your pregnancy.',
  'Team ParentVeda',
  '6 min read',
  ARRAY['books', 'pregnancy guide']::text[],
  NULL,
  NULL,
  NULL,
  '{"title":"What to Expect When You''re Expecting","author":"Heidi Murkoff"}'::jsonb,
  '2026-04-15'::timestamptz,
  '2026-04-15'::timestamptz
where not exists (
  select 1 from public.content_posts
  where category = 'book-summary' and slug = 'what-to-expect-when-youre-expecting-summary'
);

-- book-summary/ina-mays-guide-to-childbirth-summary
insert into public.content_posts (
  status, category, slug, title, description, excerpt, body, author,
  reading_time, tags, trimester, recipe, source, book_meta,
  published_at, updated_at
)
select
  'published',
  'book-summary',
  'ina-mays-guide-to-childbirth-summary',
  'Ina May''s Guide to Childbirth — key takeaways',
  'A short summary of Ina May Gaskin''s ''Guide to Childbirth'' — what it teaches about trusting your body, relaxation and birth without fear.',
  'A beloved book on confident, calmer birth. Here are its core ideas, distilled.',
  'Ina May Gaskin''s book is famous for one quietly radical idea: that fear and tension make birth harder, and calm confidence can make it gentler.

## Key takeaways

- Relaxation matters — a tense body works against itself in labour.
- Birth stories, told positively, can replace fear with confidence.
- Your support and surroundings shape your experience more than most expect.

## Our calm note

Whatever birth you plan or experience, the spirit of the book travels well: prepare, breathe, trust your body, and surround yourself with calm. There''s no single ''right'' way to bring a baby into the world.

> Note: ParentVeda offers gentle, evidence-informed guidance — not medical advice. Always check with your doctor for decisions about your pregnancy.',
  'Team ParentVeda',
  '5 min read',
  ARRAY['books', 'birth', 'third trimester']::text[],
  'third',
  NULL,
  NULL,
  '{"title":"Ina May''s Guide to Childbirth","author":"Ina May Gaskin"}'::jsonb,
  '2026-04-22'::timestamptz,
  '2026-04-22'::timestamptz
where not exists (
  select 1 from public.content_posts
  where category = 'book-summary' and slug = 'ina-mays-guide-to-childbirth-summary'
);

-- recipe/moong-dal-khichdi-pregnancy-recipe
insert into public.content_posts (
  status, category, slug, title, description, excerpt, body, author,
  reading_time, tags, trimester, recipe, source, book_meta,
  published_at, updated_at
)
select
  'published',
  'recipe',
  'moong-dal-khichdi-pregnancy-recipe',
  'Moong dal khichdi for pregnancy — gentle, iron-rich comfort',
  'An easy moong dal khichdi recipe for pregnancy — warm, light, easy to digest and quietly nourishing. Ready in about 30 minutes.',
  'Comfort in a single bowl: soft, warming and easy on a tired tummy. A trimester-three favourite.',
  'Khichdi is the gentlest of foods — soft, warm and easy to digest, which makes it perfect when your appetite is small or your tummy is tender. Moong dal adds protein and a little iron without feeling heavy.

> Note: Tip: a spoon of ghee and a side of curd make it more nourishing and even easier to digest. ParentVeda offers gentle, evidence-informed guidance — not medical advice. Always check with your doctor for decisions about your pregnancy.',
  'Team ParentVeda',
  '3 min read',
  ARRAY['recipe', 'third trimester', 'comfort food']::text[],
  'third',
  '{"prepTime":"10 min","cookTime":"20 min","totalTime":"30 min","servings":"Serves 2","ingredients":["1/2 cup rice, rinsed","1/2 cup yellow moong dal, rinsed","1 tbsp ghee","1/2 tsp cumin (jeera) seeds","A pinch of hing (asafoetida)","1/2 tsp turmeric (haldi)","1-inch ginger, finely chopped","3 cups water (more for a softer khichdi)","Salt to taste"],"steps":["Soak the rice and moong dal together for 10 minutes while you prep.","Heat ghee in a pressure cooker. Add cumin and hing; let them sizzle.","Add ginger and turmeric, then the drained rice and dal. Stir for a minute.","Add water and salt. Pressure cook for 3–4 whistles until very soft.","Let the pressure release naturally. Stir, adjust water to a soft consistency, and serve warm with a little extra ghee and curd."]}'::jsonb,
  NULL,
  NULL,
  '2026-05-08'::timestamptz,
  '2026-05-08'::timestamptz
where not exists (
  select 1 from public.content_posts
  where category = 'recipe' and slug = 'moong-dal-khichdi-pregnancy-recipe'
);

-- recipe/lemon-ginger-water-pregnancy-nausea-recipe
insert into public.content_posts (
  status, category, slug, title, description, excerpt, body, author,
  reading_time, tags, trimester, recipe, source, book_meta,
  published_at, updated_at
)
select
  'published',
  'recipe',
  'lemon-ginger-water-pregnancy-nausea-recipe',
  'Lemon-ginger morning water for pregnancy nausea',
  'A simple lemon-ginger water to ease early-pregnancy nausea (ji-michli). A gentle 5-minute morning settler — sip slowly.',
  'A calming morning settler for queasy early-trimester days. Five minutes, three ingredients.',
  'Morning ji-michli (nausea) is one of the most common early-pregnancy companions. Ginger has a long, well-loved reputation for soothing it, and a little lemon makes it easier to sip.

> Note: Keep it gentle — a small glass, sipped slowly. If nausea is severe or you can''t keep fluids down, speak to your doctor. ParentVeda offers gentle, evidence-informed guidance — not medical advice. Always check with your doctor for decisions about your pregnancy.',
  'Team ParentVeda',
  '2 min read',
  ARRAY['nushkhe', 'first trimester', 'nausea']::text[],
  'first',
  '{"prepTime":"5 min","cookTime":"0 min","totalTime":"5 min","servings":"1 glass","ingredients":["1 cup warm water","1/2-inch fresh ginger, lightly crushed","1 tsp lemon juice","1/2 tsp honey (optional)"],"steps":["Steep the crushed ginger in warm water for 3–4 minutes.","Strain, then stir in the lemon juice (and honey if using).","Sip slowly — small sips settle a queasy stomach better than gulping."]}'::jsonb,
  NULL,
  NULL,
  '2026-05-15'::timestamptz,
  '2026-05-15'::timestamptz
where not exists (
  select 1 from public.content_posts
  where category = 'recipe' and slug = 'lemon-ginger-water-pregnancy-nausea-recipe'
);

-- parenting-faq/can-i-eat-papaya-during-pregnancy
insert into public.content_posts (
  status, category, slug, title, description, excerpt, body, author,
  reading_time, tags, trimester, recipe, source, book_meta,
  published_at, updated_at
)
select
  'published',
  'parenting-faq',
  'can-i-eat-papaya-during-pregnancy',
  'Can I eat papaya during pregnancy?',
  'Is papaya safe in pregnancy? The short answer: ripe papaya in small amounts is usually fine; raw or unripe papaya is best avoided. Here''s why.',
  'The short answer, and the reasoning behind the popular worry — ripe vs. raw papaya in pregnancy.',
  'The short answer: ripe papaya in small amounts is usually considered fine, while raw or unripe papaya is the one traditionally advised against.

## Why the difference?

Unripe (green) papaya contains more of a substance called latex, which is the source of the long-standing caution. Fully ripe papaya has very little of it, and also offers vitamins and fibre.

- Ripe papaya, in moderation: generally considered okay for most pregnancies.
- Raw / unripe papaya: best avoided, especially as a large or regular portion.

> Note: Every pregnancy is different — if you have a specific condition or any doubt, check with your doctor. ParentVeda offers gentle, evidence-informed guidance — not medical advice. Always check with your doctor for decisions about your pregnancy.',
  'Team ParentVeda',
  '3 min read',
  ARRAY['food safety', 'nutrition', 'first trimester']::text[],
  'first',
  NULL,
  NULL,
  NULL,
  '2026-05-25'::timestamptz,
  '2026-05-25'::timestamptz
where not exists (
  select 1 from public.content_posts
  where category = 'parenting-faq' and slug = 'can-i-eat-papaya-during-pregnancy'
);

-- parenting-faq/is-it-safe-to-sleep-on-your-back-during-pregnancy
insert into public.content_posts (
  status, category, slug, title, description, excerpt, body, author,
  reading_time, tags, trimester, recipe, source, book_meta,
  published_at, updated_at
)
select
  'published',
  'parenting-faq',
  'is-it-safe-to-sleep-on-your-back-during-pregnancy',
  'Is it safe to sleep on your back during pregnancy?',
  'Back-sleeping in later pregnancy can feel uncomfortable for a reason. Why side-sleeping (especially the left) is usually recommended from the second half.',
  'Why side-sleeping is usually recommended later in pregnancy — and how to make it comfortable.',
  'In early pregnancy, sleep in whatever position feels comfortable. From around the middle of pregnancy onward, many doctors suggest favouring your side rather than your back.

## Why side-sleeping?

As your bump grows, lying flat on your back can press on a major blood vessel and feel uncomfortable or light-headed. Sleeping on your side — the left is often suggested — keeps blood flowing comfortably to you and your baby.

## Making it comfortable

- Tuck a pillow between your knees and under your bump.
- If you wake on your back, simply roll back to your side — no need to worry.

> Note: ParentVeda offers gentle, evidence-informed guidance — not medical advice. Always check with your doctor for decisions about your pregnancy.',
  'Team ParentVeda',
  '3 min read',
  ARRAY['sleep', 'second trimester', 'third trimester']::text[],
  'second',
  NULL,
  NULL,
  NULL,
  '2026-06-01'::timestamptz,
  '2026-06-01'::timestamptz
where not exists (
  select 1 from public.content_posts
  where category = 'parenting-faq' and slug = 'is-it-safe-to-sleep-on-your-back-during-pregnancy'
);

-- Sanity check — expect the 10 rows above, plus anything already in Directus.
select status, category, slug, title
from public.content_posts
order by category, slug;

